server:
  port: 8002
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/users
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    stream:
      bindings:
        input:
          destination: departments
          content-type: application/json
          group: departments
defaultDepartmentId: 2