spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.13/users
    username: admin
    password: "{cipher}dae561b74c0094a7a9cbe1e39c388600b2cce09dc97b9587c90802a47603289c"
  jpa:
    hibernate:
      ddl-auto: create
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.0.17
          zk-nodes: 192.168.0.17